from task1 import BinarySearchTree
bst = BinarySearchTree()
bst.CreateTree()
bst.insertNode(100)
bst.insertNode(50)
bst.insertNode(200)
bst.insertNode(300)
bst.insertNode(20)
bst.insertNode(150)
bst.insertNode(70)
bst.insertNode(180)
bst.insertNode(120)
bst.insertNode(30)
print(bst.preOrder())
print(bst.inOrder())
print(bst.postOrder())